version: '3.8'

services:
    mongodbApp:
        container_name: mongodb-app
        image: mongo
        restart: on-failure
        ports:
            - 27017:27017
        networks:
            - nesjs-network
        volumes:
            - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: tasks
    dev:
        depends_on:
          - mongodbApp
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        environment:
            MONGODB_URI: mongodb://root:password@mongodbApp/tasks
    prod:
        depends_on:
          - mongodbApp
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run buildstart:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: on-failure
        environment:
            MONGODB_URI: mongodb://root:password@mongodbApp/tasks

networks:
    nesjs-network: