version: '3.1'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tasks

  mongo-express:
    image: mongo-express
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password

      #- ME_CONFIG_BASICAUTH_USERNAME=root
      #- ME_CONFIG_BASICAUTH_PASSWORD=password

      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      
      - ME_CONFIG_MONGODB_PORT=27017